services:
  r-app:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    command: sleep infinity
    ports:
      - ${PORT:-2222}:${PORT:-2222}
    environment:
      PORT: ${PORT:-2222}
