name: cran-update.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3 * * *'

permissions: read-all

jobs:
  cran-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: ghcr.io/r-hub/cran-metadata:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: www
    - name: Update
      run: |
        ln -s `pwd`/www $PROJECT_ROOT/www
        quarto render $PROJECT_ROOT
    - name: test
      run: cd www; git status
    - name: Deploy to GitHub pages 🚀
      if: false
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        clean: false
        branch: gh-pages
        folder: www
