name: cran-update.yml
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3 * * *'

permissions: read-all

jobs:
  cran-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: gaborcsardi/run-r-app@main
