name: test.yaml
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build and push app
      uses: gaborcsardi/build-r-app@main
      with:
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
        ghcr-token: ${{ secrets.GITHUB_TOKEN }}
        push: false
